name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          echo "${{ secrets.OPENAI_API_KEY }}" >> .env

      # Set up Python environment with compatible version
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Create Python virtual environment and install dependencies in one script
      - name: Create Python virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            # Install with specific compatible versions to avoid conflicts
            pip install numpy<3 pandas<3 scikit-learn<1.6 scipy<1.15
            pip install -r requirements.txt
          fi
