name: Node.js & Python CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci
        
      # 5. Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 6. Create Python virtual environment and install dependencies
      - name: Create Python virtual environment and install dependencies
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            # Install specific compatible versions to avoid conflicts
            pip install numpy<3 pandas<3 scikit-learn<1.6 scipy<1.15
            pip install -r requirements.txt
          fi

      # Optional: Run your tests (Node.js tests or Python tests)
      - name: Run Node.js tests
        run: npm test

      - name: Run Python tests
        shell: bash
        run: |
          source venv/bin/activate
          if [ -f requirements.txt ]; then
            pytest
          fi
